/** Getter **/
export const GET_LESSONS = '[Lesson] GET_LESSONS'
export const GET_LESSON = '[Lesson] GET_LESSON'
export const GET_LESSONS_COUNT = '[Lesson] GET_LESSONS_COUNT'
export const GET_LESSON_IDS = '[Lesson] GET_LESSON_IDS'

/** Actions **/
export const ADD_LESSON_ACTION = '[Lesson] ADD_LESSON_ACTION'
export const ADD_LESSONS_ACTION = '[Lesson] ADD_LESSONS_ACTION'
export const REPLACE_LESSONS_ACTION = '[Lesson] REPLACE_LESSONS_ACTION'
export const UPDATE_LESSON_ACTION = '[Lesson] UPDATE_LESSON_ACTION'
export const UPDATE_LESSONS_ACTION = '[Lesson] UPDATE_LESSONS_ACTION'
export const REMOVE_LESSON_ACTION = '[Lesson] REMOVE_LESSON_ACTION'
export const REMOVE_LESSONS_ACTION = '[Lesson] REMOVE_LESSONS_ACTION'
export const REMOVE_ALL_LESSONS_ACTION = '[Lesson] REMOVE_ALL_LESSONS_ACTION'
export const UPSERT_LESSON_ACTION = '[Lesson] UPSERT_LESSON_ACTION'
export const UPSERT_LESSONS_ACTION = '[Lesson] UPSERT_LESSONS_ACTION'

/** Mutations **/
export const ADD_LESSON_MUTATION = '[Lesson] ADD_LESSON_MUTATION'
export const ADD_LESSONS_MUTATION = '[Lesson] ADD_LESSONS_MUTATION'
export const REPLACE_LESSONS_MUTATION = '[Lesson] REPLACE_LESSONS_MUTATION'
export const UPDATE_LESSON_MUTATION = '[Lesson] UPDATE_LESSON_MUTATION'
export const UPDATE_LESSONS_MUTATION = '[Lesson] UPDATE_LESSONS_MUTATION'
export const REMOVE_LESSON_MUTATION = '[Lesson] REMOVE_LESSON_MUTATION'
export const REMOVE_LESSONS_MUTATION = '[Lesson] REMOVE_LESSONS_MUTATION'
export const REMOVE_ALL_LESSONS_MUTATION = '[Lesson] REMOVE_ALL_LESSONS_MUTATION'
export const UPSERT_LESSON_MUTATION = '[Lesson] UPSERT_LESSON_MUTATION'
export const UPSERT_LESSONS_MUTATION = '[Lesson] UPSERT_LESSONS_MUTATION'
